---
- hosts: all
  gather_facts: false

  pre_tasks:
    - name: Setup Teleport connectivity
      ansible.builtin.include_role:
        name: awx-teleport-connector

    - name: Gathering facts
      ansible.builtin.setup:

  tasks:
    - name: Hello World
      ansible.builtin.debug:
        msg: |-
          Hostname: {{ inventory_hostname }}
          IP: {{ ansible_default_ipv4.address }}
          Family: {{ ansible_facts['os_family'] }}
          Distro: {{ ansible_facts['distribution'] }}
          Version: {{ ansible_facts['distribution_version'] }}
