---
- hosts: all
  gather_facts: false

  pre_tasks:
    - name: Setup Teleport connectivity
      ansible.builtin.include_tasks: teleport/setup.yaml
      run_once: true
      vars:
        ansible_connection: local

    - name: Gather facts
      ansible.builtin.setup:

  tasks:
    - name: Hello World
      ansible.builtin.debug:
        msg: "Howdy {{ ansible_facts['distribution'] }}"
