---
- hosts: all

  tasks:
    - name: Setup Teleport connectivity
      ansible.builtin.include_tasks: teleport/setup.yaml
      vars:
        ansible_connection: local

    - name: Hello World
      ansible.builtin.debug:
        msg: "Howdy {{ ansible_facts['distribution'] }}"
