---
- name: Create Ansible SSH configuration
  ansible.builtin.template:
    src: "ssh_config.j2"
    dest: "{{ file_ssh_pub_key | dirname }}/ssh_config"
  no_log: "{{ no_log }}"

- name: Copy identity to correct location
  ansible.builtin.copy:
    src: "{{ file_ssh_teleport_identity }}"
    dest: "{{ file_ssh_teleport_identity | dirname }}/identity"
    remote_src: true

# Ensure trailing newlines in files otherwise ssh fails to load the files
- name: Ensure posix line endings
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    line: ""
    insertafter: "EOF"
  with_items:
    - "{{ file_ssh_priv_key }}"
    - "{{ file_ssh_pub_key }}"
    - "{{ file_ssh_teleport_identity | dirname }}/identity"

- name: Set ansible configuration facts
  ansible.builtin.set_fact:
    ansible_ssh_args: "-F {{ file_ssh_pub_key | dirname }}/ssh_config"

- name: Dump key
  ansible.builtin.command:
    cmd: cat {{ file_ssh_priv_key }}
