---
- name: Create temporary ID directory
  ansible.builtin.tempfile:
    state: directory
  register: temp_id_dir

- name: Create Teleport identity
  ansible.builtin.copy:
    content: "{{ teleport_identity }}"
    dest: "{{ temp_id_dir.path}}/identity"
  no_log: true

- name: Create SSH private key file
  ansible.builtin.copy:
    content: "{{ ssh_priv_key }}"
    dest: "{{ temp_id_dir.path }}/key"
    mode: 0600
  no_log: true

- name: Create SSH public key file
  ansible.builtin.copy:
    content: "{{ ssh_pub_key }}"
    dest: "{{ temp_id_dir.path }}/key-cert.pub"

- name: Create SSH known hosts file
  ansible.builtin.copy:
    content: "{{ ssh_known_hosts }}"
    dest: "{{ temp_id_dir.path }}/known_hosts"

- name: Create Ansible SSH configuration
  ansible.builtin.template:
    src: "ssh_config.j2"
    dest: "{{ temp_id_dir.path }}/ssh_config"
  no_log: true

- name: Set ansible configuration facts
  ansible.builtin.set_fact:
    ansible_ssh_args: "-F {{ temp_id_dir.path }}/ssh_config"
