---
- name: Create Ansible SSH configuration
  ansible.builtin.template:
    src: "ssh_config.j2"
    dest: "{{ file_ssh_pub_key | dirname }}/ssh_config"
  no_log: "{{ no_log }}"

# SSH has some expectations on file names for matching pub/priv keys
- name: Copy files to correct names
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: true
  with_items:
    - src: "{{ file_ssh_known_hosts }}"
      dest: "{{ file_ssh_known_hosts | dirname }}/known_hosts"
    - src: "{{ file_ssh_pub_key }}"
      dest: "{{ file_ssh_pub_key | dirname }}/key-cert.pub"
    - src: "{{ file_ssh_priv_key }}"
      dest: "{{ file_ssh_priv_key | dirname }}/key"
    - src: "{{ file_ssh_teleport_identity }}"
      dest: "{{ file_ssh_teleport_identity | dirname }}/identity"

- name: Set ansible configuration facts
  ansible.builtin.set_fact:
    ansible_ssh_args: "-F {{ file_ssh_pub_key | dirname }}/ssh_config -vv"
