---
- name: Create Ansible SSH configuration
  ansible.builtin.template:
    src: "ssh_config.j2"
    dest: "{{ file_ssh_pub_key | dirname }}/ssh_config"
  no_log: "{{ no_log }}"

- name: Copy identity to correct location
  ansible.builtin.copy:
    src: "{{ file_ssh_teleport_identity }}"
    dest: "{{ file_ssh_teleport_identity | dirname }}/identity"
    remote_src: true

# If there isn't a trailing new line then ssh fails to load the private key
- name: Ensure trailing new line in the SSH private key
  ansible.builtin.lineinfile:
    path: "{{ file_ssh_priv_key }}"
    line: ""
    insertafter: "EOF"

- name: Ensure trailing new line in the Teleport identity file
  ansible.builtin.lineinfile:
    path: "{{ file_ssh_teleport_identity }}"
    line: ""
    insertafter: "EOF"

- name: Set ansible configuration facts
  ansible.builtin.set_fact:
    ansible_ssh_args: "-F {{ file_ssh_pub_key | dirname }}/ssh_config"

- name: Dump key
  ansible.builtin.command:
    cmd: cat {{ file_ssh_priv_key }}
