---
- name: Create Ansible SSH configuration
  ansible.builtin.template:
    src: "ssh_config.j2"
    dest: "{{ file_ssh_pub_key | dirname }}/ssh_config"
  no_log: "{{ no_log }}"

- name: Set ansible configuration facts
  ansible.builtin.set_fact:
    ansible_ssh_args: "-F {{ file_ssh_pub_key | dirname }}/ssh_config"

- name: Dump config file
  ansible.builtin.command:
    cmd: 'cat {{ file_ssh_pub_key | dirname }}/ssh_config'

- name: Dump priv key
  ansible.builtin.command:
    cmd: 'cat {{ file_ssh_priv_key }}'

- name: Dump pub key
  ansible.builtin.command:
    cmd: 'cat {{ file_ssh_pub_key }}'

- name: Dump known hosts file
  ansible.builtin.command:
    cmd: 'cat {{ file_ssh_known_hosts }}'
